%%{init: {'theme':'base', 'themeVariables': {'fontSize':'18px', 'edgeLabelBackground':'#FFFFFF'}}}%%
flowchart TB
    n0[/SCENARIO Initial Data/]
    n1(MODEL 2 RL Generator<br/>Warm Start)
    n2(GENETIC ALGORITHM<br/>NSGA II)
    n3[/PARETO FRONT <br/>optimal solutions/]
    n4(MODEL 1 RECOMMENDER<br/>RL + Fuzzy)
    n5[/SOLUTION + EXPLANATION/]
    n6{{USER <br/>Human in Loop}}
    n7[/FEEDBACK/]

    n0 --> n1
    n1 --> n2
    n2 --> n3
    n3 --> n4
    n4 --> n5
    n5 --> n6
    n6 --> n7
    n7 -.->|Retraining| n4
    n7 -.->|Retraining| n1

    style n0 fill:#FFFFFF,stroke:#333333
    style n1 fill:#B0C4DE,stroke:#333333
    style n2 fill:#B0C4DE,stroke:#333333
    style n3 fill:#E8F4F8,stroke:#333333
    style n4 fill:#B0C4DE,stroke:#333333
    style n5 fill:#E8F4F8,stroke:#333333
    style n6 fill:#87CEEB,stroke:#333333
    style n7 fill:#FFFFFF,stroke:#333333
    linkStyle 7 font-size:22px
    linkStyle 8 font-size:22px